-- Guesthouse (Vila Silvia) schema — corrected to match the real production
-- database exactly, pulled via a live connection to the old Supabase Cloud
-- project rather than just inferred from admin.html's JS. Two corrections
-- from an earlier draft: services/minibar use text ids (e.g. 'cola',
-- 'sauna', matching the catalog_id values used in admin.html), and
-- room_prices uses room_type itself as the primary key (no separate id).
--
-- RLS NOTE: this is a single-tenant internal tool (one guesthouse, one
-- staff team) — not a multi-tenant SaaS app. The policies below simply
-- require the caller to be an authenticated (logged-in) user; they do
-- NOT distinguish between staff roles. If you later want e.g. a
-- "read-only" role, or per-user restrictions, tighten these policies —
-- each one is flagged below with what it currently allows.

create extension if not exists "pgcrypto";

create table public.reservations (
  id bigint generated by default as identity primary key,
  guest text not null,
  phone text,
  room text not null check (room in ('Standard', 'Apartament')),
  room_number integer not null,
  source text not null default 'direct' check (source in ('booking', 'direct')),
  status text not null default 'reserved' check (status in ('reserved', 'paid', 'checkedin', 'cancelled')),
  checkin date not null,
  checkout date not null,
  price numeric(10, 2) not null default 0,
  group_id text,
  guests integer,
  constraint reservations_dates_valid check (checkout > checkin)
);

create table public.extras (
  id bigint generated by default as identity primary key,
  reservation_id bigint not null references public.reservations (id) on delete cascade,
  catalog_id text, -- references services.id or minibar.id, loosely (not a real FK: the two catalogs share this column)
  type text not null check (type in ('service', 'minibar')),
  name text not null,
  price numeric(10, 2) not null default 0,
  qty integer not null default 1
);

create table public.room_prices (
  room_type text primary key,
  price numeric(10, 2) not null default 0,
  base_occupancy integer not null default 2,
  extra_person_price numeric(10, 2) not null default 0
);

create table public.services (
  id text primary key,
  name text not null,
  price numeric(10, 2) not null default 0
);

create table public.minibar (
  id text primary key,
  name text not null,
  price numeric(10, 2) not null default 0,
  stock integer not null default 0
);

create table public.expenses (
  id bigint generated by default as identity primary key,
  date date not null,
  category text not null,
  note text,
  amount numeric(10, 2) not null default 0
);

create table public.maintenance (
  id bigint generated by default as identity primary key,
  room_number integer not null,
  from_date date not null,
  to_date date not null,
  reason text
);

create table public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

create index reservations_status_idx on public.reservations (status);
create index reservations_room_number_idx on public.reservations (room_number);
create index extras_reservation_id_idx on public.extras (reservation_id);
create index maintenance_room_number_idx on public.maintenance (room_number);

-- --- Row Level Security ---
-- FLAG: every policy below just checks `auth.role() = 'authenticated'`,
-- i.e. "any logged-in staff member can do anything." Review in Supabase
-- Studio (Authentication > Policies) once real staff accounts exist, and
-- tighten if you want e.g. a read-only front-desk role vs. an owner role.

alter table public.reservations enable row level security;
alter table public.extras enable row level security;
alter table public.room_prices enable row level security;
alter table public.services enable row level security;
alter table public.minibar enable row level security;
alter table public.expenses enable row level security;
alter table public.maintenance enable row level security;
alter table public.push_subscriptions enable row level security;

create policy "authenticated full access" on public.reservations
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.extras
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.room_prices
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.services
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.minibar
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.expenses
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated full access" on public.maintenance
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated can manage push subscriptions" on public.push_subscriptions
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
