-- Adds a guests table (grouping a person's reservation history across
-- stays, with editable notes/preferences) and a "noshow" status, both
-- needed for the admin panel's Guest History modal and Archived tab.
--
-- Existing reservations are backfilled into guests, matched by phone
-- number where present (the more reliable identifier), falling back to
-- an exact name match when no phone is on file.
--
-- NOTE: targets the "public" schema, not "vila_silvia". Migration 0003
-- (move to a dedicated schema) was written and committed but never
-- actually run against the live database — confirmed live on
-- 2026-09-21 (schema "vila_silvia" does not exist; all 20 existing
-- reservations are still in public.reservations). This migration
-- matches the database as it actually is today.

create table public.guests (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.reservations add column guest_id bigint references public.guests (id);

do $$
declare
  r record;
  g_id bigint;
begin
  for r in
    select distinct guest as full_name, nullif(trim(phone), '') as phone
    from public.reservations
    where guest_id is null
  loop
    g_id := null;
    if r.phone is not null then
      select id into g_id from public.guests where phone = r.phone limit 1;
    end if;

    if g_id is null then
      insert into public.guests (full_name, phone)
      values (r.full_name, r.phone)
      returning id into g_id;
    end if;

    update public.reservations
    set guest_id = g_id
    where guest_id is null
      and guest = r.full_name
      and coalesce(nullif(trim(phone), ''), '') = coalesce(r.phone, '');
  end loop;
end $$;

alter table public.reservations alter column guest_id set not null;

-- "noshow" joins "cancelled" in the Archived tab (reservations that
-- never resulted in a stay), distinct from a normal checked-out guest.
alter table public.reservations drop constraint if exists reservations_status_check;
alter table public.reservations add constraint reservations_status_check
  check (status in ('reserved', 'paid', 'checkedin', 'cancelled', 'noshow'));

alter table public.guests enable row level security;
create policy "authenticated full access" on public.guests
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
